### PR TITLE
Add Settings ViewController to customize badge, notifications, and update frequency

### PR DESCRIPTION
**Pull request by danydev**
Hi, this is a pull request to add some settings so that the user is able to enable\disable badge notification, notification center notifications, and decide the frequency update (at launch, daily, weekly, monthly, never)

screen shot 2015-05-31 at 14 57 47

### CODE REVIEW

**Comment by danydev** [comment]
Hey @stonesam92 , did you take a look at the pull request? :)

**Comment by danydev** [comment]
@stonesam92 Updated with master

**Comment by stonesam92** [comment]
Hi @danydev, sorry for being so unresponsive. I've been really busy over the past few weeks first with university exams and now I'm away and don't have access to a proper computer. I'll be back home towards the end of the coming week and will take a closer look at this code then before I merge it.

Thanks for making these changes, especially the minor style fixes to my code which are a pain to do, and sorry for taking so long to reply!

**Comment by danydev** [comment]
Closing, since whatsapp web already provides this feature (click on the 3 vertical points and then "Notifications")

**Pull request closed without merging**
