### PR TITLE
Updated for El Capitan compatibility + Updated the icon set

### PR DESCRIPTION
**Pull request by avatsaev**

### CODE REVIEW

**Comment by yangshun** [comment]
Hmm the original logo resembled WhatsApp's logo and was changed to what it is now to avoid legal issues. The logo shouldn't be changed back..

**Comment by stonesam92** [comment]
Thanks for these, but as @yangshun described, ChitChat really attempts to stay well clear of WhatsApp's intellectual property, and including unlicensed uses of the copyrighted WhatsApp logo would go against this idea.

The other fixes were also submitted in an earlier PR by another contributor, so I merged those instead.

Thanks so much for contributing to the project though!

**Comment by avatsaev** [comment]
I have a question though, why can't I drag the window anymore? Several other users are reporting the same issue to me.

**Comment by yangshun** [comment]
Works for me though

**Comment by avatsaev** [comment]
OS version?

**Comment by yangshun** [comment]
Oh I'm still on Mavericks

**Comment by avatsaev** [comment]
El Cap here, must the 10.11 related issue

**Pull request closed without merging**
