### PR TITLE
Added status bar item.

### PR DESCRIPTION
**Pull request by congbach**

### CODE REVIEW

**Comment by yangshun** [comment]
Lol @congbach nice to see you contributing to ChitChat too! :smile:

**Comment by stonesam92** [comment]
Thank you very much for adding this.

However, WhatsApp have a history of attacking projects which misuse their intellectual property or break their terms of service, and so I'm extremely reluctant to include any resources in the project containing WhatsApp's copyrighted material such as the icon used in this PR.

ChitChat's icon was clearly inspired by the original WhatsApp logo, but is sufficiently different that it does not mislead anyone into believing that ChitChat is an official WhatsApp product.

If you could make another set of icon's using ChitChat's icon design (logo embedded in a circle rather than speech bubble, the phone is a custom design and is facing downwards), then I will merge this.

Thanks

**Comment by yangshun** [comment]
I'll take a stab at this over the weekend. I have some design experience (:

**Comment by congbach** [comment]
That'd be great. thanks a lot! :)

**Comment by tschoffelen** [comment]
I noticed there wasn't much activity here, so I decided to go and quickly try something myself. 
Up to @congbach to add them to the PR if he think's they're alright.

Sketch file here: https://drive.google.com/folderview?id=0B2G1jqsrP6PfcnhsdFk0dFhLd28&usp=sharing

statusiconread
statusiconread 2x
statusiconunread
statusiconunread 2x

I also thought that it might be fun to do the unread one in green instead of blue:

statusiconunreadgreen
statusiconunreadgreen 2x

**Comment by yangshun** [comment]
@tschoffelen looks good! (:

**Comment by stonesam92** [comment]
@tschoffelen these look great, thanks!

If @congbach would add these to the PR, I'd be happy to merge it!

**Comment by congbach** [comment]
@tschoffelen: looks great, thanks a lot!
@stonesam92: I've pushed a new commit with @tschoffelen's images. Thanks!

**Comment by yangshun** [comment]
:+1:

**Comment by stonesam92** [comment]
Thanks, everybody!

**Comment by joostrijneveld** [comment]
Can someone elaborate on the purpose of this status bar icon? Clicking it brings the app to the front, which is exactly what the dock icon already does. What is the added benefit that warrants the added status bar clutter?

**Pull request merged**
